repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
